import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import {Sidebar} from "@/app/components/Sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex min-h-screen">
          {/* Fixed Sidebar */}
          <aside className="w-64 bg-gray-100 border-r border-gray-200 fixed h-full">
              <Sidebar />
          </aside>

          {/* Main Content Area */}
          <main className="flex-1 ml-64 p-8 bg-white">
              {children}
          </main>
      </div>
      <Toaster position={'top-center'} richColors={true}/>
      </body>
    </html>
  );
}
